"""add creator_id to tasks

Revision ID: 3afb3ae90564
Revises: 78524f970d07
Create Date: 2026-02-12 14:55:53.460457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afb3ae90564'
down_revision: Union[str, Sequence[str], None] = '78524f970d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
