"""add is_public to projects

Revision ID: 78524f970d07
Revises: 8e67c1c7bffb
Create Date: 2026-02-12 14:47:51.631041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78524f970d07'
down_revision: Union[str, Sequence[str], None] = '8e67c1c7bffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###
