"""add role to user

Revision ID: 8e67c1c7bffb
Revises: 740ec240a677
Create Date: 2026-02-11 15:14:15.588447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e67c1c7bffb'
down_revision: Union[str, Sequence[str], None] = '740ec240a677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    # Make column non-nullable
    op.alter_column('users', 'role', nullable=False)
    # Drop old column
    op.drop_column('users', 'is_superuser')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
