"""add project_stack and ai_generation models

Revision ID: ac8cea52e8b7
Revises: 5b317012f6a7
Create Date: 2026-02-14 17:55:52.164865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8cea52e8b7'
down_revision: Union[str, Sequence[str], None] = '5b317012f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('generation_type', sa.String(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_content', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_id'), 'ai_generations', ['id'], unique=False)
    op.create_table('project_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('test_framework', sa.String(), nullable=True),
    sa.Column('containerized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_project_stacks_id'), 'project_stacks', ['id'], unique=False)
    op.create_index(op.f('ix_task_activities_id'), 'task_activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_activities_id'), table_name='task_activities')
    op.drop_index(op.f('ix_project_stacks_id'), table_name='project_stacks')
    op.drop_table('project_stacks')
    op.drop_index(op.f('ix_ai_generations_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    # ### end Alembic commands ###
